/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package connectionviewer;

import connectionviewer.ConnectionViewerPanel;

/**
 *
 * @author mrupp
 */
public class Clip extends javax.swing.JFrame
{

	/**
	 * Creates new form Clip
	 */
	public Clip()
	{
		initComponents();
	}

	ConnectionViewerPanel cwp;
	Clip(ConnectionViewerPanel a)
	{
		cwp = a;
		initComponents();		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSliderXStart = new javax.swing.JSlider();
        jSliderXStop = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSliderYStart = new javax.swing.JSlider();
        jSliderYStop = new javax.swing.JSlider();
        jSliderZStart = new javax.swing.JSlider();
        jSliderZStop = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ConnectionViewer Clip");
        setAlwaysOnTop(true);
        setResizable(false);

        jSliderXStart.setValue(0);
        jSliderXStart.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSliderXStartStateChanged(evt);
            }
        });

        jSliderXStop.setValue(100);
        jSliderXStop.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSliderXStopStateChanged(evt);
            }
        });

        jLabel1.setText("x Clip");

        jLabel2.setText("y Clip");

        jLabel3.setText("z Clip");

        jSliderYStart.setValue(0);
        jSliderYStart.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSliderYStartStateChanged(evt);
            }
        });

        jSliderYStop.setValue(100);
        jSliderYStop.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSliderYStopStateChanged(evt);
            }
        });

        jSliderZStart.setValue(0);
        jSliderZStart.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSliderZStartStateChanged(evt);
            }
        });

        jSliderZStop.setValue(100);
        jSliderZStop.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSliderZStopStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(80, 80, 80)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(jLabel2)))
                            .add(layout.createSequentialGroup()
                                .add(75, 75, 75)
                                .add(jLabel3)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSliderXStop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSliderXStart, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jSliderYStop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSliderYStart, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jSliderZStop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSliderZStart, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSliderXStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSliderXStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSliderYStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSliderYStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSliderZStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSliderZStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderXStartStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderXStartStateChanged
    {//GEN-HEADEREND:event_jSliderXStartStateChanged
        cwp.xminFactor = jSliderXStart.getValue()*0.01;
        cwp.repaint();
    }//GEN-LAST:event_jSliderXStartStateChanged

    private void jSliderXStopStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderXStopStateChanged
    {//GEN-HEADEREND:event_jSliderXStopStateChanged
        cwp.xmaxFactor = jSliderXStop.getValue()*0.01;
        cwp.repaint();
    }//GEN-LAST:event_jSliderXStopStateChanged

    private void jSliderYStartStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderYStartStateChanged
    {//GEN-HEADEREND:event_jSliderYStartStateChanged
        cwp.yminFactor = jSliderYStart.getValue()*0.01;
        cwp.repaint();
    }//GEN-LAST:event_jSliderYStartStateChanged

    private void jSliderYStopStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderYStopStateChanged
    {//GEN-HEADEREND:event_jSliderYStopStateChanged
        cwp.ymaxFactor = jSliderYStop.getValue()*0.01;
        cwp.repaint();
    }//GEN-LAST:event_jSliderYStopStateChanged

    private void jSliderZStartStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderZStartStateChanged
    {//GEN-HEADEREND:event_jSliderZStartStateChanged
        cwp.zminFactor = jSliderZStart.getValue()*0.01;
        cwp.repaint();
    }//GEN-LAST:event_jSliderZStartStateChanged

    private void jSliderZStopStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderZStopStateChanged
    {//GEN-HEADEREND:event_jSliderZStopStateChanged
        cwp.zmaxFactor = jSliderZStop.getValue()*0.01;
        cwp.repaint();
    }//GEN-LAST:event_jSliderZStopStateChanged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(Clip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(Clip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(Clip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(Clip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new Clip().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider jSliderXStart;
    private javax.swing.JSlider jSliderXStop;
    private javax.swing.JSlider jSliderYStart;
    private javax.swing.JSlider jSliderYStop;
    private javax.swing.JSlider jSliderZStart;
    private javax.swing.JSlider jSliderZStop;
    // End of variables declaration//GEN-END:variables
}
